//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kortros.ManageTab.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kortros.ManageTab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #АР Задания
        ///00_Общие уровни и сетки
        ///01. АР_Вспомогательные элементы
        ///02. АР_Гидроизоляция
        ///03. АР_Двери и окна
        ///04. АР_ЖБ
        ///05. АР_Засыпка
        ///06. АР_Кладка
        ///07. АР_Кладка наружная
        ///08. АР_Кровля
        ///09. АР_Крыльца
        ///10. АР_Лотки
        ///11. АР_Фасад
        ///12. АР_Оборудование
        ///13. АР_Ограждения
        ///14. АР_Отверстия в кладке
        ///15. АР_Отделка 
        ///16. АР_Перемычки
        ///17. АР_Сантехнические приборы
        ///18. АР_Технология
        ///19. АР_Зоны проезда
        ///20. АР_Фахверки.
        /// </summary>
        internal static string WorksetToImport_AR {
            get {
                return ResourceManager.GetString("WorksetToImport_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 000_Link_AR
        ///000_Link_KR
        ///000_Link_VK
        ///000_Link_OV
        ///000_Link_EOM
        ///000_Link_SS.
        /// </summary>
        internal static string WorksetToImport_LINK {
            get {
                return ResourceManager.GetString("WorksetToImport_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01.Общеобменная вентиляция
        ///02.Противодымная вентиляция
        ///03.Существующие воздуховоды
        ///04.Отопление
        ///05.Теплоснабжение
        ///06.Холодоснабжение
        ///07.Дренаж
        ///08.Хладоцентр
        ///09.ОЗК
        ///10.Оборудование.
        /// </summary>
        internal static string WorksetToImport_OV {
            get {
                return ResourceManager.GetString("WorksetToImport_OV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01.Оборудование
        ///02.АТП
        ///03.ЛВС
        ///04.ОС
        ///05.ПС
        ///06.РФ
        ///07.СВН
        ///08.СКУД
        ///09.СОУЭ
        ///10.СС.
        /// </summary>
        internal static string WorksetToImport_SS {
            get {
                return ResourceManager.GetString("WorksetToImport_SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01.ВК_Хозяйственно-питьевой водопровод (В1)
        ///02.ВК_Горячее водоснабжение (Т3, Т4)
        ///03.ВК_Хозяйственно бытовая канализация (К1, К1Н)
        ///04.ВК_Прозводственная канализация (К3,К3Н)
        ///05.ВК_Ливневая канализация (К2,К2Н)
        ///06.ВК_Дренажная канализация (К21)
        ///07.ВК_Дренаж фанкойлов (К23)
        ///08.ВК_Удаление  ОТВ (К24)
        ///09.ПТ_АУПТ
        ///10.ПТ_ВПВ
        ///11.Оборудование
        ///12.Сантехнические приборы.
        /// </summary>
        internal static string WorksetToImport_VK {
            get {
                return ResourceManager.GetString("WorksetToImport_VK", resourceCulture);
            }
        }
    }
}
