//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kortros.General.UpdateParameters.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class UpdateParameter : global::System.Configuration.ApplicationSettingsBase {
        
        private static UpdateParameter defaultInstance = ((UpdateParameter)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UpdateParameter())));
        
        public static UpdateParameter Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("495d66c9-c5b5-493e-9b0f-73afc67e4216")]
        public global::System.Guid ParameterKolichestvo {
            get {
                return ((global::System.Guid)(this["ParameterKolichestvo"]));
            }
            set {
                this["ParameterKolichestvo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7621a737-0095-43fe-93fd-ee4a267a6cab")]
        public global::System.Guid ParameterIzmer {
            get {
                return ((global::System.Guid)(this["ParameterIzmer"]));
            }
            set {
                this["ParameterIzmer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("663814f3-e83a-447f-a1d5-866c8c082409")]
        public global::System.Guid ParameterGroup {
            get {
                return ((global::System.Guid)(this["ParameterGroup"]));
            }
            set {
                this["ParameterGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateParameterSelectedKolichestvo {
            get {
                return ((bool)(this["UpdateParameterSelectedKolichestvo"]));
            }
            set {
                this["UpdateParameterSelectedKolichestvo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateParameterSelectedIzmer {
            get {
                return ((bool)(this["UpdateParameterSelectedIzmer"]));
            }
            set {
                this["UpdateParameterSelectedIzmer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateParameterSelectedGroup {
            get {
                return ((bool)(this["UpdateParameterSelectedGroup"]));
            }
            set {
                this["UpdateParameterSelectedGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateParameterSelectedWorkset {
            get {
                return ((bool)(this["UpdateParameterSelectedWorkset"]));
            }
            set {
                this["UpdateParameterSelectedWorkset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateParameterSelectedElementId {
            get {
                return ((bool)(this["UpdateParameterSelectedElementId"]));
            }
            set {
                this["UpdateParameterSelectedElementId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdateParameterUpdateOnlySelected {
            get {
                return ((bool)(this["UpdateParameterUpdateOnlySelected"]));
            }
            set {
                this["UpdateParameterUpdateOnlySelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("495ac66d-09f7-466e-b85a-59f70db13553")]
        public global::System.Guid ParameterElementId {
            get {
                return ((global::System.Guid)(this["ParameterElementId"]));
            }
            set {
                this["ParameterElementId"] = value;
            }
        }
    }
}
